sudo: false

git:
  depth: 3

branches:
  only:
    - next
    - master

language: node_js

node_versions: &versions
  - lts/*
  - node

os:
  - linux
  # - windows

cache:
  npm: true

jobs:
  include:
    # - stage: lint âœ¨
    #   script: npm run lint

    - stage: test ğŸ‘©ğŸ½â€ğŸ’»
      script: npm test:cov
      node_js: *versions
