sudo: false

git:
  depth: 3

branches:
  only:
    - next
    - master

language: node_js

cache:
  npm: true

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint âœ¨
      script: npm run lint:ci
      node_js: lts/*

    - stage: test ğŸ‘©ğŸ½â€ğŸ’»
      script: npm run test:cov
      node_js: node
    - node_js: lts/*
    - os: windows
      node_js: node
    - os: windows
      node_js: lts/*
